import { createServer } from 'node:http';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { join, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'out');
const MIME = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp','.ico':'image/x-icon','.txt':'text/plain','.xml':'application/xml'};
const server = createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://x').pathname);let f=join(out,p);if(existsSync(f)&&statSync(f).isDirectory())f=join(f,'index.html');if(!existsSync(f))f=join(out,p.replace(/\/$/,'')+'.html');if(!existsSync(f)){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':MIME[extname(f)]??'application/octet-stream'});res.end(readFileSync(f))});
await new Promise(r=>server.listen(4872,r));
const browser = await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:'new',args:['--no-sandbox']});
const dir = '/private/tmp/claude-502/-Users-damyvt-development/f9e27fda-ee8c-4dbb-a640-355149ca1cd9/scratchpad';
const page = await browser.newPage();
await page.setViewport({width:1440,height:900,deviceScaleFactor:1});
await page.goto('http://localhost:4872/',{waitUntil:'networkidle0'});
await new Promise(r=>setTimeout(r,800));
await page.screenshot({path:join(dir,'shot-landing-top.png')});
await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight*0.45));
await new Promise(r=>setTimeout(r,500));
await page.screenshot({path:join(dir,'shot-landing-mid.png')});
await page.evaluate(()=>window.scrollTo(0,0));
// open demo
await page.click('[data-testid="open-demo"]');
await page.waitForSelector('[data-testid="grid"]',{timeout:20000});
await page.waitForFunction(()=>document.querySelectorAll('[data-testid="cell"] img').length>=9,{timeout:30000});
await new Promise(r=>setTimeout(r,600));
await page.keyboard.press('p');
await page.keyboard.press('ArrowRight');
await page.keyboard.press('3');
await page.keyboard.press('ArrowRight');
await page.keyboard.press('x');
await new Promise(r=>setTimeout(r,300));
await page.screenshot({path:join(dir,'shot-grid.png')});
await page.keyboard.press('ArrowLeft');
await page.keyboard.press('Enter');
await page.waitForSelector('[data-testid="loupe"]');
await new Promise(r=>setTimeout(r,1500));
await page.screenshot({path:join(dir,'shot-loupe.png')});
await page.keyboard.press('e');
await new Promise(r=>setTimeout(r,500));
await page.screenshot({path:join(dir,'shot-export.png')});
await browser.close();server.close();console.log('done');
